
default: &default
  adapter: <%= ENV["ADAPTER"] %>
  encoding: unicode
  host: <%= ENV["HOST"] %>
  port: <%= ENV["PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: true
  prepared_statements: false

development:
  <<: *default
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  <<: *default

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>